services:
  postgres:
    image: postgres:16
    container_name: etle-postgres
    environment:
      POSTGRES_USER: etle
      POSTGRES_PASSWORD: etlepass
      POSTGRES_DB: etle_db
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - etle_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  etle_pgdata:
